group group
version version

apply plugin: 'groovy'
apply plugin: 'maven-publish'

sourceSets {
    main {
        groovy {
            exclude 'com/lcg/plugin/AutoFieldTransform.groovy'
            exclude 'com/lcg/plugin/ActivityAutoFieldTransform.groovy'
            exclude 'com/lcg/plugin/FragmentAutoFieldTransform.groovy'
            exclude 'com/lcg/plugin/ObserverAutoFieldTransform.groovy'
        }
    }
}

buildscript {

    repositories {
        google()
        mavenCentral()
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'com.android.tools.build:gradle-api:9.1.0'
    implementation 'org.ow2.asm:asm-tree:9.7.1'
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.ow2.asm:asm-util:9.7.1'
}

afterEvaluate {
    publishing {
//    配置maven-publishing插件的输出物
        publications {
            maven(MavenPublication) {
                artifactId = 'auto-field'
                from components.java
            }
        }
        repositories {
            maven {
                url = layout.projectDirectory.dir('../repo')
            }
        }
    }
}
