group group
version version

apply plugin: 'groovy'
apply plugin: 'maven-publish'
buildscript {

    repositories {
        google()
        mavenCentral()
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation 'com.android.tools.build:gradle-api:9.1.0'
    implementation 'org.javassist:javassist:3.23.1-GA'
    implementation 'commons-io:commons-io:2.21.0'
}

afterEvaluate {
    publishing {
//    配置maven-publishing插件的输出物
        publications {
            maven(MavenPublication) {
                artifactId = 'auto-field'
                from components.java
            }
        }
        repositories {
            maven {
                url = layout.projectDirectory.dir('../repo')
            }
        }
    }
}