apply plugin: 'groovy'
apply plugin: 'maven-publish'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
    options.release = 11
}

tasks.withType(GroovyCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_11.toString()
    targetCompatibility = JavaVersion.VERSION_11.toString()
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    compileOnly 'com.android.tools.build:gradle-api:9.1.0'
    implementation 'org.ow2.asm:asm-tree:9.7.1'
}

afterEvaluate {
    publishing {
//    配置maven-publishing插件的输出物
        publications {
            maven(MavenPublication) {
                artifactId = 'auto-field'
                from components.java
            }
        }
        repositories {
            maven {
                url = layout.projectDirectory.dir('../repo')
            }
        }
    }
}
